version: "3.9"
services:
  postgres:
    container_name: journal_database
    image: "postgres:15.1-alpine"
    environment:
      - POSTGRES_PASSWORD=123456
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5400:5432"
    networks:
      - journal
    profiles:
      ["journal", "postgres"]

networks:
  journal:
    name: Journal
