targets:
  $default:
    builders:
      source_gen|combining_builder:
        options:
          build_extensions:
            '^lib/models/{{}}.dart': 'lib/models/generated/{{}}.g.dart'
            '^lib/models2/{{}}.dart': 'lib/models2/generated/{{}}.g.dart'